#pragma once

const int DOT_SIZE = 16;
const int DOT_NUM = 64;
const int PAINTING_SIZE = DOT_NUM * DOT_SIZE;

enum GRAPH {
	GRAPH_NONE,
	GRAPH_FRAME,
	GRAPH_SCREEN_PAST,
	GRAPH_SCREEN_FUTURE,
	GRAPH_SCREEN_CHARACTER,
	GRAPH_FUTURE_DOT,
	GRAPH_PAST_DOT,
	GRAPH_CHARACTER,
	GRAPH_ITEM
};